### PR TITLE
ARM64 support

### PR DESCRIPTION
**Pull request by leaanthony**
Thanks to the amazing work of @stffabi, we can now support ARM64!

### CODE REVIEW

**Comment by jchv** [comment]
Awesome. I don’t currently have an ARM64 Windows machine to test on, but the diff looks trivially good to me. (I would bet winloader is broken on ARM64 though :)

**Comment by stffabi** [comment]
winloader worked fine on my ARM64 VM 😄

**Comment by stffabi** [comment]
Thanks for merging.

**Comment by jchv** [comment]
No problem, thanks for contributing. Winloader working on ARM is a pleasant surprise. It’s supposed to, but was never tested. I was expecting to have forgotten an ICache invalidation or similar.

**Pull request merged**
